### PR TITLE
GenDefault class to derive generators

### PR DESCRIPTION
**Pull request by ejconlon**
Implements the design in #49 . Defines `GenDefault` class to derive generators with support for user-defined tags to select implementations. Also includes various `DerivingVia` helpers.

### CODE REVIEW

**Comment by edsko** [comment]
Apologies for the slow reaction, I've been so busy. But this is really nice work! I like it. Thank you for your attention to detail. I think the only thing we should consider how we could make `Test.Falsify.Generator.Default` and `Test.Falsify.Generator.Tag` not be siblings, but instead clarify in the module hierarchy that one is an instance of the other. Perhaps `Test.Falsify.Generator.Default` and `Test.Falsify.Generator.Default.Falsify`? That double `Falsify` is a tad annoying but it does make sense. Maybe even `Test.Falsify.GenDefault` and ` `Test.Falsify.GenDefault.Falsify`? 

Alternatively, maybe, `Test.Falsify.Generator.ClassBased` and `Test.Falsify.Generator.ClassBased.Default`? That's perhaps a little cleaner, what do you think?

But once we resolve that, this is ready to merge. Sorry again for the delay!

**Comment by ejconlon** [comment]
@edsko You presented a few good options. What do you think about `Test.Falsify.GenDefault` and `Test.Falsify.GenDefault.Std`? We can change the name of the default tag to `Std` as well, to indicate that this is the standard set of generators. These are short module names that match their contents, so I think they will be easy for people to remember.

**Comment by edsko** [comment]
Yes, I like it :) Thank you!

**Comment by ejconlon** [comment]
@edsko Oops, forgot to add to exposed modules! (I use hpack for everything else...) https://github.com/well-typed/falsify/pull/64

**Pull request merged**
